
export const CAR_LOGIN_REQUEST = "CAR_LOGIN_REQUEST";
export const CAR_LOGIN_SUCCESS = "CAR_LOGIN_SUCCESS";
export const CAR_LOGIN_FAIL = "CAR_LOGIN_FAIL";
export const CAR_LOGOUT = "CAR_LOGOUT";

export const CAR_REGISTER_REQUEST = "CAR_REGISTER_REQUEST";
export const CAR_REGISTER_SUCCESS = "CAR_REGISTER_SUCCESS";
export const CAR_REGISTER_FAIL = "CAR_REGISTER_FAIL";

export const CAR_LIST_REQUEST = "CAR_LIST_REQUEST";
export const CAR_LIST_SUCCESS = "CAR_LIST_SUCCESS";
export const CAR_LIST_FAIL = "CAR_LIST_FAIL";
export const CAR_LIST_RESET = "CAR_LIST_RESET";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL";
export const CAR_DETAILS_RESET = "CAR_DETAILS_RESET";

export const CAR_PROFILE_REQUEST = "CAR_PROFILE_REQUEST";
export const CAR_PROFILE_SUCCESS = "CAR_PROFILE_SUCCESS";
export const CAR_PROFILE_FAIL = "CAR_PROFILE_FAIL";
export const CAR_PROFILE_RESET = "CAR_PROFILE_RESET";

export const CAR_UPDATE_PROFILE_REQUEST = "CAR_UPDATE_PROFILE_REQUEST";
export const CAR_UPDATE_PROFILE_SUCCESS = "CAR_UPDATE_PROFILE_SUCCESS";
export const CAR_UPDATE_PROFILE_FAIL = "CAR_UPDATE_PROFILE_FAIL";
export const CAR_UPDATE_PROFILE_RESET = "CAR_UPDATE_PROFILE_RESET";

export const CAR_DELETE_REQUEST = "CAR_DELETE_REQUEST";
export const CAR_DELETE_SUCCESS = "CAR_DELETE_SUCCESS";
export const CAR_DELETE_FAIL = "CAR_DELETE_FAIL";
export const CAR_DELETE_RESET = "CAR_DELETE_RESET";
