export const COMPANY_LOGIN_REQUEST = "COMPANY_LOGIN_REQUEST";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS";
export const COMPANY_LOGIN_FAIL = "COMPANY_LOGIN_FAIL";
export const COMPANY_LOGOUT = "COMPANY_LOGOUT";

export const COMPANY_REGISTER_REQUEST = "COMPANY_REGISTER_REQUEST";
export const COMPANY_REGISTER_SUCCESS = "COMPANY_REGISTER_SUCCESS";
export const COMPANY_REGISTER_FAIL = "COMPANY_REGISTER_FAIL";

export const COMPANY_LIST_REQUEST = "COMPANY_LIST_REQUEST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAIL = "COMPANY_LIST_FAIL";
export const COMPANY_LIST_RESET = "COMPANY_LIST_RESET";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";
export const COMPANY_DETAILS_RESET = "COMPANY_DETAILS_RESET";

export const COMPANY_PROFILE_REQUEST = "COMPANY_PROFILE_REQUEST";
export const COMPANY_PROFILE_SUCCESS = "COMPANY_PROFILE_SUCCESS";
export const COMPANY_PROFILE_FAIL = "COMPANY_PROFILE_FAIL";
export const COMPANY_PROFILE_RESET = "COMPANY_PROFILE_RESET";

export const COMPANY_UPDATE_PROFILE_REQUEST = "COMPANY_UPDATE_PROFILE_REQUEST";
export const COMPANY_UPDATE_PROFILE_SUCCESS = "COMPANY_UPDATE_PROFILE_SUCCESS";
export const COMPANY_UPDATE_PROFILE_FAIL = "COMPANY_UPDATE_PROFILE_FAIL";
export const COMPANY_UPDATE_PROFILE_RESET = "COMPANY_UPDATE_PROFILE_RESET";

export const COMPANY_DELETE_REQUEST = "COMPANY_DELETE_REQUEST";
export const COMPANY_DELETE_SUCCESS = "COMPANY_DELETE_SUCCESS";
export const COMPANY_DELETE_FAIL = "COMPANY_DELETE_FAIL";
export const COMPANY_DELETE_RESET = "COMPANY_DELETE_RESET";
